"""fix transaction amount column

Revision ID: 10d6a0ff160f
Revises: 93b03ce10a5d
Create Date: 2026-01-08 22:32:41.204072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d6a0ff160f'
down_revision: Union[str, None] = '93b03ce10a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('limit', sa.Float(), nullable=False))
    op.drop_column('transactions', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'limit')
    # ### end Alembic commands ###
