"""rename transaction limit to amount

Revision ID: fa61fc6c8435
Revises: a6ab481c6d36
Create Date: 2026-01-08 22:44:43.575984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa61fc6c8435'
down_revision: Union[str, None] = 'a6ab481c6d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('amount', sa.Float(), nullable=False))
    op.drop_column('transactions', 'limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'amount')
    # ### end Alembic commands ###
